### ISSUE TITLE
Why are outliers at both ends of the sequence

### ISSUE THREAD

**Issue by pjgao** [y-bar/ml-based-anomaly-detection#14]
```python
x = np.linspace(0, 10, 2000)
y = np.sin(x)+np.sin(5*x)+np.cos(x)
y[1450:1460] = 2.1
y[600:603] = 2.2
noise = np.random.uniform(0, 0.3, len(y))
y += noise

s = Silency(3, 10, 10)
saliency_map = s.transform_spectral_residual(y)
fig, ax = plt.subplots(2, 1, figsize=(10, 5), sharex=True)
ax[0].plot(x, y, c='#6495ed', label='Time series')
ax[1].plot(x, saliency_map, c='#6495ed', label='Saliency map')
mask = saliency_map > 0.2
ax[0].plot(x[mask], y[mask], marker='x', c='r', linestyle='')
ax[1].plot(x[mask], saliency_map[mask], marker='x', c='r', linestyle='')
for i in ax:
    i.legend()
```
![image](https://user-images.githubusercontent.com/22350313/116838410-d8ab1400-ac00-11eb-87ee-60a4feb2d6c5.png)

**Comment by lushunn** [comment]
The paper https://arxiv.org/abs/1906.03821 have said " However, the SR method works better if the target point locates in the center of the sliding window", you can use "Silency.generate_anomaly_score" to generate Saliency map, instead of  "transform_spectral_residual", because it extends the array in the end of the sequence.
`x = np.linspace(0, 10, 2000)
y = np.sin(x)+np.sin(5*x)+np.cos(x)
y[1450:1460] = 2.1
y[600:603] = 2.2
noise = np.random.uniform(0, 0.3, len(y))
y += noise

s = anom.Silency(3, 10,20)
saliency_map = s.generate_anomaly_score(y)
fig, ax = plt.subplots(2, 1, figsize=(10, 5), sharex=True)
ax[0].plot(x, y, c='#6495ed', label='Time series')
ax[1].plot(x, saliency_map, c='#6495ed', label='Saliency map')
mask = saliency_map > 4
ax[0].plot(x[mask], y[mask], marker='x', c='r', linestyle='')
ax[1].plot(x[mask], saliency_map[mask], marker='x', c='r', linestyle='')
for i in ax:
    i.legend()`

**Comment by lushunn** [comment]
The paper https://arxiv.org/abs/1906.03821 have said " However, the SR method works better if the target point locates in the center of the sliding window", you can use "Silency.generate_anomaly_score" to generate Saliency map, instead of "transform_spectral_residual", because it extends the array in the end of the sequence.
```python
x = np.linspace(0, 10, 2000)
y = np.sin(x)+np.sin(5*x)+np.cos(x)
y[1450:1460] = 2.1
y[600:603] = 2.2
noise = np.random.uniform(0, 0.3, len(y))
y += noise

s = anom.Silency(3, 10,20)
saliency_map = s.generate_anomaly_score(y)
fig, ax = plt.subplots(2, 1, figsize=(10, 5), sharex=True)
ax[0].plot(x, y, c='#6495ed', label='Time series')
ax[1].plot(x, saliency_map, c='#6495ed', label='Saliency map')
mask = saliency_map > 4
ax[0].plot(x[mask], y[mask], marker='x', c='r', linestyle='')
ax[1].plot(x[mask], saliency_map[mask], marker='x', c='r', linestyle='')
for i in ax:
    i.legend()
```

**Comment by pjgao** [comment]
Thanks very much!
